language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

branches:
  only:
    - master
before_install:
  - gem update --system
  - gem --version

notifications:
  email:
    recipients:
      - creynoso@plangrade.com
    on_failure: change
    on_success: never
